### ISSUE TITLE
Training on Kinetics-600 not reproducible | NumPy ValueError

### ISSUE THREAD

**Issue by MartGro** [Tobi-r9/RaMViD#1]
Hello, 
when trying to reproduce the training on the Kinetics-600 dataset, I encountered a ValueError. 
The installation is a fresh enroot installation according to the process outlined in the repo. 
Any idea where this error comes from?

Best,
Martin

```
 python scripts/video_train.py --data_dir /workspace/datasets/kinetics_dataset/validate/ $MODEL_FLAGS $DIFFUSION_FLAGS $TRAIN_FLAGS
1
Logging to /tmp/openai-2022-11-04-08-17-39-336300
-----------------------------------------------------------
| anneal_type            | None                           |
| attention_resolutions  | 16,8                           |
| batch_size             | 2                              |
| class_cond             | 0                              |
| clip                   | 1                              |
| data_dir               | /workspace/datasets/kinetic... |
| decay                  | 0                              |
| diffusion_steps        | 1e+03                          |
| drop                   | 0                              |
| dropout                | 0                              |
| ema_rate               | 0.9999                         |
| exclude_conditional    | 1                              |
| fp16_scale_growth      | 0.001                          |
| image_size             | 64                             |
| learn_sigma            | 0                              |
| log_interval           | 10                             |
| lr                     | 2e-05                          |
| lr_anneal_steps        | 0                              |
| mask_range             | None                           |
| max_num_mask_frames    | 4                              |
| microbatch             | 1                              |
| noise_schedule         | linear                         |
| num_channels           | 128                            |
| num_heads              | 4                              |
| num_heads_upsample     | -1                             |
| num_res_blocks         | 3                              |
| predict_xstart         | 0                              |
| rescale_learned_sigmas | 1                              |
| rescale_timesteps      | 1                              |
| resume_checkpoint      |                                |
| rgb                    | 1                              |
| save_interval          | 2e+03                          |
| scale_time_dim         | 0                              |
| schedule_sampler       | uniform                        |
| seed                   | 123                            |
| seq_len                | 16                             |
| sigma_small            | 0                              |
| steps_drop             | 0                              |
| timestep_respacing     |                                |
| uncondition_rate       | 0.25                           |
| use_checkpoint         | 0                              |
| use_fp16               | 0                              |
| use_kl                 | 0                              |
| use_scale_shift_norm   | 1                              |
| weight_decay           | 0                              |
-----------------------------------------------------------
creating model and diffusion...
cuda:0
creating data loader...
training...
global batch size = 2
world_size: 1
/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py:475: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
WARNING:libav.avi:Packet corrupt (stream = 0, dts = 515)
WARNING:libav.avi:.
ERROR:libav.NULL:Invalid NAL unit size (1289 > 752).
ERROR:libav.NULL:missing picture in access unit with size 756
ERROR:libav.h264:Invalid NAL unit size (1289 > 752).
ERROR:libav.h264:Error splitting the input into NAL units.
------------------------
| grad_norm | 1        |
| loss      | 1        |
| loss_q0   | 0.998    |
| loss_q2   | 1        |
| mse       | 1        |
| mse_q0    | 0.998    |
| mse_q2    | 1        |
| samples   | 2        |
| step      | 0        |
------------------------
saving model 0...
saving model 0.9999...
Traceback (most recent call last):
  File "scripts/video_train.py", line 126, in <module>
    main()
  File "scripts/video_train.py", line 64, in main
    TrainLoop(
  File "/workspace/RaMViD/diffusion_openai/train_util.py", line 197, in run_loop
    batch, cond = next(self.data)
  File "/workspace/RaMViD/diffusion_openai/video_datasets.py", line 70, in load_data
    yield from loader
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 518, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1180, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1226, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/RaMViD/diffusion_openai/video_datasets.py", line 132, in __getitem__
    arr_seq = np.transpose(arr_seq, [3, 0, 1, 2])
  File "<__array_function__ internals>", line 5, in transpose
  File "/opt/conda/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 658, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/opt/conda/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array
```

**Comment by Tobi-r9** [comment]
Hi Maritn,
I cannot reproduce the error. Which version of av do you use?
Also, there might be a problem with the dataset. It seems that some videos are corrupted. Are you able to load some videos or do you get this error for each video?
Best Tobi
